FROM openjdk:21

COPY ./test-center-service/target/test-center-service-0.0.1-SNAPSHOT.jar /app/test-center-service-0.0.1-SNAPSHOT.jar

EXPOSE 9191

CMD ["java", "-jar", "/app/test-center-service-0.0.1-SNAPSHOT.jar"]


